apiVersion: v1
kind: ConfigMap
metadata:
  name: imperial-court-config
  namespace: default
data:
  EMBED_MODEL: "text-embedding-3-small"
  QDRANT_COLLECTION: "imperial_court_kb"
  MOCK_MODE: "false"
  DB_SSL_ALLOW_SELF_SIGNED: "true"
  CREWAI_TRACING_ENABLED: "true"

---
apiVersion: v1
kind: Secret
metadata:
  name: imperial-court-secrets
  namespace: default
type: Opaque
stringData:
  OPENAI_API_KEY: "your-openai-api-key"
  QDRANT_URL: "your-qdrant-url"
  QDRANT_API_KEY: "your-qdrant-api-key"
  SUPABASE_DB_URL: "your-supabase-db-url"
  CELERY_BROKER_URL: "your-redis-url"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imperial-court-fastapi
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: imperial-court-fastapi
  template:
    metadata:
      labels:
        app: imperial-court-fastapi
    spec:
      containers:
        - name: fastapi
          image: your-registry.com/imperial-court-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: imperial-court-secrets
                  key: OPENAI_API_KEY
            - name: QDRANT_URL
              valueFrom:
                secretKeyRef:
                  name: imperial-court-secrets
                  key: QDRANT_URL
            - name: QDRANT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: imperial-court-secrets
                  key: QDRANT_API_KEY
            - name: SUPABASE_DB_URL
              valueFrom:
                secretKeyRef:
                  name: imperial-court-secrets
                  key: SUPABASE_DB_URL
            - name: CELERY_BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: imperial-court-secrets
                  key: CELERY_BROKER_URL
          envFrom:
            - configMapRef:
                name: imperial-court-config
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: imperial-court-fastapi-service
  namespace: default
spec:
  selector:
    app: imperial-court-fastapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imperial-court-celery-worker
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: imperial-court-celery-worker
  template:
    metadata:
      labels:
        app: imperial-court-celery-worker
    spec:
      containers:
        - name: celery-worker
          image: your-registry.com/imperial-court-backend:latest
          command:
            [
              "celery",
              "--app=app.celery_config.celery_app",
              "worker",
              "--loglevel=info",
              "--concurrency=2",
            ]
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: imperial-court-secrets
                  key: OPENAI_API_KEY
            - name: QDRANT_URL
              valueFrom:
                secretKeyRef:
                  name: imperial-court-secrets
                  key: QDRANT_URL
            - name: QDRANT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: imperial-court-secrets
                  key: QDRANT_API_KEY
            - name: SUPABASE_DB_URL
              valueFrom:
                secretKeyRef:
                  name: imperial-court-secrets
                  key: SUPABASE_DB_URL
            - name: CELERY_BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: imperial-court-secrets
                  key: CELERY_BROKER_URL
          envFrom:
            - configMapRef:
                name: imperial-court-config
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
